# This configuration file tells Mike where to find prebuilt .bin files (Travis
# builds them) and where to find the tests.

binaries:
    prebuilt_s3: adafruit-circuit-python
    file_pattern: bin/{board}/adafruit-circuitpython-{board}-*-{short_sha}.bin

circuitpython_tests:
    test_directories:
        - tests/basics
        - tests/circuitpython
